# -*- coding: utf-8 -*-
"""Learning flywheel — the factory learns from its OWN output quality (closes the OODA loop).

Reads the flight-recorder (3_MEMORY/factory_metrics.jsonl, written per render by factory_metrics)
and aggregates by TEMPLATE + script-source using the FREE per-render signals we already produce
(verify-pass + script-lint warnings — no Gemini/publish/analytics needed). Emits:
  • 3_MEMORY/template_scores.json  — machine-readable {template: {n, pass_rate, avg_lint}};
    make_video._weak_templates() reads it and DROPS empirically-weak templates from rotation.
  • 3_MEMORY/HOT_LEARNINGS.md      — human-readable ranking + lessons.

Run periodically (after a batch):  python 4_BRAIN/learn_flywheel.py  /  npm run factory:learn
Pattern adopted from Upload-Post/skill-autoshorts HOT.md flywheel, re-implemented native + free.
"""
import json
import os
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
METRICS = ROOT / "3_MEMORY" / "factory_metrics.jsonl"
SCORES = ROOT / "3_MEMORY" / "template_scores.json"
HOT = ROOT / "3_MEMORY" / "HOT_LEARNINGS.md"
MIN_N = 3   # need >=3 samples before trusting a template's score


def _rows():
    if not METRICS.exists():
        return []
    out = []
    for ln in METRICS.read_text(encoding="utf-8").splitlines():
        if ln.strip():
            try:
                out.append(json.loads(ln))
            except Exception:
                pass
    return out


def learn():
    rows = _rows()
    if not rows:
        print("[flywheel] no metrics yet — render some videos first (npm run factory:metrics).")
        return {}
    by_t = defaultdict(lambda: {"n": 0, "ok": 0, "lint": 0})
    by_s = defaultdict(lambda: {"n": 0, "ok": 0})
    for r in rows:
        t = r.get("template") or "?"
        by_t[t]["n"] += 1
        by_t[t]["ok"] += 1 if r.get("ok") else 0
        by_t[t]["lint"] += r.get("lint_warns") or 0
        s = r.get("script") or "?"
        by_s[s]["n"] += 1
        by_s[s]["ok"] += 1 if r.get("ok") else 0

    scores = {t: {"n": v["n"], "pass_rate": round(v["ok"] / v["n"], 2),
                  "avg_lint": round(v["lint"] / v["n"], 1)} for t, v in by_t.items()}
    SCORES.parent.mkdir(parents=True, exist_ok=True)
    SCORES.write_text(json.dumps(scores, ensure_ascii=False, indent=1), encoding="utf-8")

    # ranking: trusted (n>=MIN_N) first, by pass_rate desc then avg_lint asc
    ranked = sorted(scores.items(),
                    key=lambda kv: (kv[1]["n"] >= MIN_N, kv[1]["pass_rate"], -kv[1]["avg_lint"]),
                    reverse=True)
    weak = [t for t, v in scores.items() if v["n"] >= MIN_N and v["pass_rate"] < 0.7]
    lines = ["# HOT Learnings — what the factory learned from its own output",
             f"\n_{len(rows)} renders analyzed. Auto-generated by `npm run factory:learn`._\n",
             "## Templates (pass-rate · avg lint-warnings · samples)"]
    for t, v in ranked:
        mark = "⚠️ WEAK (dropped from rotation)" if t in weak else ("" if v["n"] >= MIN_N else "_(few samples)_")
        lines.append(f"- **{t}** — pass {int(v['pass_rate']*100)}% · lint {v['avg_lint']} · n={v['n']} {mark}")
    lines.append("\n## Script source")
    for s, v in by_s.items():
        lines.append(f"- {s}: {int(100*v['ok']/v['n'])}% pass (n={v['n']})")
    if weak:
        lines.append(f"\n**Action:** `make_video._rot` now skips {weak} (empirically <70% pass).")
    HOT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[flywheel] {len(rows)} renders → {len(scores)} templates ranked. "
          f"Weak (dropped): {weak or 'none'}. Wrote template_scores.json + HOT_LEARNINGS.md")
    return scores


if __name__ == "__main__":
    learn()
