# -*- coding: utf-8 -*-
"""Generate a browsable CATALOG of the SEOSONA element/motion kho — so the whole resource pool is
visible at a glance (element types, icons, emojis, Lottie animations, photos). Writes a markdown index
(+ optionally a visual icon board). Run: `python scripts/build_element_catalog.py`.
"""
import os, sys, json

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "2_SKILLS", "element_maker"))
OUT = os.path.join(ROOT, "2_KNOWLEDGE", "style_references", "talking_head", "ELEMENT-KHO-CATALOG.md")


def _names(d, ext):
    return sorted(os.path.splitext(f)[0] for f in os.listdir(d) if f.endswith(ext)) if os.path.isdir(d) else []


def main():
    import element_maker as em
    icons = _names(em.ICON_DIR, ".svg")
    lottie = _names(em.LOTTIE_DIR, ".json")
    twemoji = _names(em.TWEMOJI_DIR, ".svg")
    photos = _names(os.path.join(ROOT, "7_ASSETS", "brand", "photos"), ".jpg")
    try:
        manifest = json.load(open(os.path.join(ROOT, "2_SKILLS", "element_maker", "element_library.json"), encoding="utf-8"))
        types = list(manifest.get("types", {}).keys())
    except Exception:
        types = []
    L = []
    L.append("# SEOSONA element / motion kho — catalog\n")
    L.append("Auto-generated by `scripts/build_element_catalog.py`. The full resource pool the video "
             "factory draws from (all NATIVE / headless / self-growing).\n")
    L.append(f"## Element types ({len(types)})\n`" + "` · `".join(types) + "`\n")
    L.append("Motion tiers: ffmpeg entrance (default) · animated clips `rich_motion` (pop/bounce/spin) · Lottie · "
             "native effects (count_up · confetti · kinetic · pulse_ring · progress_bar).\n")
    L.append(f"## Icons — {len(icons)} vendored (Lucide, self-growing; 1744-icon catalog auto-fetchable)\n")
    L.append(", ".join(icons) + "\n")
    L.append(f"## Lottie motion-graphics — {len(lottie)} (free, Apache-2.0)\n`" + "` · `".join(lottie) + "`\n")
    L.append(f"## Emoji — {len(twemoji)} flat Twemoji SVGs (brand-consistent) + native fallback; "
             f"{len(em.EMOJI_ALIASES)} concept aliases\n")
    L.append(f"## Photos — {len(photos)} cached (Pexels/scrape, 9:16)\n`" + "` · `".join(photos) + "`\n")
    L.append(f"## Resolvers (self-grow)\n- icons: {len(em.ICON_ALIASES)} concept aliases → auto-fetch new Lucide\n"
             f"- lottie: {len(em.LOTTIE_ALIASES)} concept aliases\n- image: Pexels search + URL scrape (image_sourcer)\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(L))
    print(f"catalog → {OUT}")
    print(f"  {len(types)} types · {len(icons)} icons · {len(lottie)} lottie · {len(twemoji)} twemoji · {len(photos)} photos")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    main()
