# -*- coding: utf-8 -*-
"""Generate the SEOSONA Video knowledge graph — the machine-readable "second brain" data file.

Pattern harvested (REFERENCE-only, no vendoring — see 2_KNOWLEDGE/INGESTION_LOG.md 2026-07-01):
Karpathy's "LLM Wiki" (AgriciDaniel/claude-obsidian), obsidian-mind, code-review-graph, dreamgraph —
the shared insight: a knowledge graph should be QUERYABLE DATA an agent traverses to work faster, not
just a picture for humans. This script SCANS THE REAL REPO (SOPs, brain modules, agents, skills,
templates, components, effects) and emits `2_KNOWLEDGE/knowledge_graph.json` — the single source of
truth that `4_BRAIN/knowledge_graph.py` queries and that feeds `docs/SYSTEM_MAP.html`'s graph view.

Re-run this whenever the system changes (new SOP, new skill, new module) instead of hand-editing the
graph — this is what makes the graph "live" rather than a stale snapshot.

  python scripts/gen_knowledge_graph.py
  python scripts/gen_knowledge_graph.py --inventory "path/to/repo_inventory.xlsx"   # optional: also
      cross-reference the ~1500-repo inventory against INGESTION_LOG.md (adds a 'repo' layer)
"""
import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUT = os.path.join(ROOT, "2_KNOWLEDGE", "knowledge_graph.json")
HTML_PATH = os.path.join(ROOT, "docs", "SYSTEM_MAP.html")
HTML_START = "  // ===== KNOWLEDGE_GRAPH_DATA_START (auto-generated by scripts/gen_knowledge_graph.py — do not hand-edit) =====\n"
HTML_END = "  // ===== KNOWLEDGE_GRAPH_DATA_END =====\n"

nodes = []
edges = []
_seen = set()


def add_node(node_id, label, group, **extra):
    if node_id in _seen:
        return
    _seen.add(node_id)
    nodes.append({"id": node_id, "label": label, "group": group, **extra})


def add_edge(a, b):
    edges.append({"from": a, "to": b})


# ============================================================================ DIRECTORIES (hub layer)
# Architectural roles are curated (not reliably inferable from filenames alone).
DIRS = [
    ("d_0inbox", "0_INPUT_INBOX", "input"), ("d_0setup", "0_SETUP", "meta"),
    ("d_1agents", "1_AGENTS", "processing"), ("d_1config", "1_CONFIG", "meta"),
    ("d_2knowledge", "2_KNOWLEDGE", "input"), ("d_2skills", "2_SKILLS", "processing"),
    ("d_3memory", "3_MEMORY", "feedback"), ("d_4brain", "4_BRAIN", "processing"),
    ("d_5framework", "5_FRAMEWORK", "processing"), ("d_6sop", "6_SOP", "meta"),
    ("d_7assets", "7_ASSETS", "input"), ("d_8workspace", "8_WORKSPACE", "output"),
    ("d_9dashboard", "9_DASHBOARD", "feedback"), ("d_9prompts", "9_PROMPTS", "input"),
    ("d_agentsskills", ".agents/skills", "processing"), ("d_scripts", "scripts/", "processing"),
    ("d_docs", "docs/", "meta"),
]
DIR_FLOW = [
    ("d_0inbox", "d_4brain"), ("d_0setup", "d_4brain"), ("d_1agents", "d_4brain"),
    ("d_4brain", "d_5framework"), ("d_2knowledge", "d_4brain"), ("d_2skills", "d_4brain"),
    ("d_6sop", "d_4brain"), ("d_7assets", "d_4brain"), ("d_9prompts", "d_4brain"),
    ("d_1config", "d_1agents"), ("d_5framework", "d_8workspace"), ("d_8workspace", "d_3memory"),
    ("d_8workspace", "d_9dashboard"), ("d_3memory", "d_9dashboard"), ("d_3memory", "d_4brain"),
    ("d_scripts", "d_4brain"), ("d_docs", "d_6sop"), ("d_agentsskills", "d_1agents"),
    ("d_agentsskills", "d_4brain"),
]


def scan_dirs():
    for node_id, label, group in DIRS:
        add_node(node_id, label, "dir", role=group)
    for a, b in DIR_FLOW:
        add_edge(a, b)


# ============================================================================ SOPs (real scan)
SOP_CATS = {
    "sopVideo": ["video_production_sop", "tech_news_faceless_sop", "talking_head_sop",
                 "COURSE_VIDEO_SOP", "repurposer_sop", "REFERENCE_TO_VIDEO_SOP",
                 "SEOSONA_VIDEO_AUTONOMOUS_TEMPLATE_FACTORY"],
    "sopVoice": ["voice_cloning_tts_sop", "VOICE_TTS_ENGINE_ROUTING", "CHIQUYET_VOICE_STYLE", "brand_voice_sop"],
    "sopRender": ["RENDER_ENGINE_DECISION", "HYPERFRAMES_INTEGRATION", "EFFECT_LIBRARY_PLAN", "MOTION_EFFECT_PLAN"],
    "sopLearning": ["AUTONOMOUS_FACTORY_LOOP", "SELF_IMPROVEMENT_LOOP", "EVAL_FLYWHEEL", "REPO_VETTING_SOP",
                    "QA_CAPTIONS_FINDINGS"],
    "sopMaps": ["SEOSONA_VIDEO_RECONNECTION_MAP", "SEOSONA_WORKFLOW_BOUNDARY_MAP", "VIDEO_ARCHITECTURE"],
    "sopPublish": ["YOUTUBE_CHANNEL_OPERATIONS_MCP", "SEO_CONTENT_STRATEGY", "youtube_seo_sop",
                   "publishing_checklist"],
    "sopDesign": ["UX_UI_DESIGN_GUIDELINES", "carousel_sop", "thumbnail_sop", "TEMPLATE_MAP"],
    "sopInfra": ["DEPENDENCIES", "GOOGLE_DRIVE_SHEETS_LAYER", "LOOP_OPERATING_SOP", "LLM_CODING_DISCIPLINE",
                 "MASTER_OPERATION", "PRODUCT_ROADMAP", "SCRIPT_WRITING_PIPELINE", "UPGRADE_BACKLOG",
                 "DASHBOARD_BUILD_PLAN", "DASHBOARD_SYSTEM_DESIGN",
                 # tombstones + deferred lanes (kept so removals stay discoverable, 2026-07-14):
                 "LIPSYNC_ENGINE_MUSETALK", "MASCOT_LIVE2D_RIG_SPEC", "LTX_BROLL_PLAN"],
}
CAT_LABEL = {"sopVideo": "Video Production", "sopVoice": "Voice & Audio", "sopRender": "Render & Framework",
             "sopLearning": "Learning & QA", "sopMaps": "Maps & Architecture", "sopPublish": "Publishing & SEO",
             "sopDesign": "Design", "sopInfra": "Infra, Ops & Strategy"}
NAME_TO_CAT = {n: cat for cat, names in SOP_CATS.items() for n in names}


def scan_sops():
    for cat, names in SOP_CATS.items():
        cat_id = "cat_" + cat
        add_node(cat_id, CAT_LABEL[cat], "sopcat")
        add_edge("d_6sop", cat_id)
    sop_dir = os.path.join(ROOT, "6_SOP")
    found, uncategorized = [], []
    for path in sorted(glob.glob(os.path.join(sop_dir, "*.md"))):
        stem = os.path.splitext(os.path.basename(path))[0]
        if stem.upper() == "README":
            continue
        found.append(stem)
        cat = NAME_TO_CAT.get(stem)
        if not cat:
            uncategorized.append(stem)
            cat = "sopInfra"  # safe fallback bucket; flagged below so it doesn't silently vanish
        node_id = "sop_" + stem
        add_node(node_id, stem, cat)
        add_edge("cat_" + cat, node_id)
    if uncategorized:
        print(f"[gen_knowledge_graph] WARNING: {len(uncategorized)} SOP(s) not in the curated category "
              f"map (filed under Infra as fallback) — update SOP_CATS: {uncategorized}")
    return len(found)


# ============================================================================ 4_BRAIN modules (real scan)
def scan_brain_modules():
    n = 0
    for path in sorted(glob.glob(os.path.join(ROOT, "4_BRAIN", "*.py"))):
        stem = os.path.splitext(os.path.basename(path))[0]
        if stem.startswith("_"):
            continue
        node_id = "b_" + stem
        add_node(node_id, stem, "brain")
        add_edge("d_4brain", node_id)
        n += 1
    return n


# ============================================================================ PIPELINE CONCEPTS (curated)
# Not filesystem-scannable — these are architectural groupings a human names, kept as a small curated
# constant (same discipline as SOP_CATS above). Update when a pipeline's PRIMARY module changes.
PIPELINES = [
    ("Script Writing Pipeline", "b_script_writer"),
    ("Master Operation", "b_workflow_router"),
    ("Effect Library Stack", "b_effect_library"),
    ("Learning Loop (OODA)", "b_factory_brain"),
    ("Two-Engine Dispatch", "b_video_engine"),
    ("Talking-Head Pipeline", "b_native_composer"),
]


def scan_pipelines():
    for i, (label, link) in enumerate(PIPELINES):
        node_id = f"p_{i}"
        add_node(node_id, label, "pipeline")
        if link in _seen:
            add_edge(node_id, link)
        else:
            print(f"[gen_knowledge_graph] WARNING: pipeline '{label}' points to missing module '{link}' "
                  f"(module renamed/removed? update PIPELINES)")
    return len(PIPELINES)


# ============================================================================ AGENTS + PERSONAS (real scan)
def scan_agents():
    agents_dir = os.path.join(ROOT, "1_AGENTS")
    n = 0
    for entry in sorted(os.listdir(agents_dir)) if os.path.isdir(agents_dir) else []:
        full = os.path.join(agents_dir, entry)
        if not os.path.isdir(full) or entry == "personas" or entry.startswith("__"):
            continue
        node_id = "ag_" + entry
        add_node(node_id, entry, "agent")
        add_edge("d_1agents", node_id)
        n += 1
    personas_dir = os.path.join(agents_dir, "personas")
    for path in sorted(glob.glob(os.path.join(personas_dir, "*.md"))):
        stem = os.path.splitext(os.path.basename(path))[0]
        if stem.upper() == "README":
            continue
        node_id = "pe_" + stem
        add_node(node_id, stem, "persona")
        add_edge("d_1agents", node_id)
        n += 1
    return n


# ============================================================================ SKILLS (real scan)
def scan_skills():
    skills_dir = os.path.join(ROOT, ".agents", "skills")
    n = 0
    for entry in sorted(os.listdir(skills_dir)) if os.path.isdir(skills_dir) else []:
        full = os.path.join(skills_dir, entry)
        if not os.path.isdir(full):
            continue
        node_id = "sk_" + entry
        add_node(node_id, entry, "skill")
        add_edge("d_agentsskills", node_id)
        n += 1
    return n


# ============================================================================ TEMPLATES (real scan)
def scan_skill_modules():
    """The 2_SKILLS capability PACKAGES (thumbnail_maker, image_sourcer, bgm_sourcer, voice_cloner,
    broll_sourcer, srt_maker, …) — real Python modules the factory calls, distinct from the .agents/skills
    SKILL.md agent skills. They were absent from the graph, so the second-brain didn't know the factory's
    own capability layer."""
    skills_dir = os.path.join(ROOT, "2_SKILLS")
    n = 0
    for entry in sorted(os.listdir(skills_dir)) if os.path.isdir(skills_dir) else []:
        full = os.path.join(skills_dir, entry)
        if not os.path.isdir(full) or entry.startswith((".", "_")):
            continue
        if not glob.glob(os.path.join(full, "*.py")):        # only packages that carry a real module
            continue
        node_id = "sm_" + entry
        add_node(node_id, entry, "skill-module")
        add_edge("d_2skills", node_id)
        n += 1
    return n


def scan_templates():
    n = 0
    for path in sorted(glob.glob(os.path.join(ROOT, "7_ASSETS", "templates", "*.json"))):
        stem = os.path.splitext(os.path.basename(path))[0]
        node_id = "tp_" + stem
        add_node(node_id, stem, "template")
        add_edge("d_7assets", node_id)
        n += 1
    return n


# ============================================================================ COMPONENTS (real scan, regex)
def scan_components():
    nc_path = os.path.join(ROOT, "4_BRAIN", "native_composer.py")
    if not os.path.exists(nc_path):
        return 0
    src = open(nc_path, encoding="utf-8").read()
    kinds = sorted(set(re.findall(r'kind\s*==\s*"([a-z-]+)"', src)))
    for kind in kinds:
        node_id = "co_" + kind
        add_node(node_id, kind, "component")
        add_edge("b_native_composer", node_id)
    return len(kinds)


# ============================================================================ EFFECT LIBRARY (real scan, import)
def scan_effects():
    sys.path.insert(0, os.path.join(ROOT, "4_BRAIN"))
    try:
        import effect_library as el
    except Exception as e:
        print(f"[gen_knowledge_graph] effect_library scan skipped: {e}")
        return 0
    n = 0
    for name in getattr(el, "TRANSITION_ORDER", []):
        add_node("fx_t_" + name, name, "fxTransition")
        add_edge("b_effect_library", "fx_t_" + name)
        n += 1
    for name in getattr(el, "TEXT_EFFECT_ORDER", []):
        add_node("fx_te_" + name, name, "fxTextEffect")
        add_edge("b_effect_library", "fx_te_" + name)
        n += 1
    for name in getattr(el, "EFFECT_ORDER", []):
        add_node("fx_e_" + name, name, "fxOverlay")
        add_edge("b_effect_library", "fx_e_" + name)
        n += 1
    for name in getattr(el, "EXIT_ORDER", []):
        add_node("fx_x_" + name, name, "fxExit")
        add_edge("b_effect_library", "fx_x_" + name)
        n += 1
    return n


# ============================================================================ DOMAIN SKILLS + ASSETS (real scan)
def scan_domain_skills():
    ds_dir = os.path.join(ROOT, "2_KNOWLEDGE", "domain_skills")
    n = 0
    for entry in sorted(os.listdir(ds_dir)) if os.path.isdir(ds_dir) else []:
        full = os.path.join(ds_dir, entry)
        if not os.path.isdir(full):
            continue
        node_id = "dk_" + entry
        add_node(node_id, entry, "domainskill")
        add_edge("d_2knowledge", node_id)
        n += 1
    return n


def scan_assets():
    n = 0
    sfx_dir = os.path.join(ROOT, "7_ASSETS", "audio", "sfx")
    for entry in sorted(os.listdir(sfx_dir)) if os.path.isdir(sfx_dir) else []:
        full = os.path.join(sfx_dir, entry)
        if os.path.isdir(full):
            node_id = "as_sfx_" + entry
            add_node(node_id, "SFX: " + entry, "asset")
            add_edge("d_7assets", node_id)
            n += 1
    for path in sorted(glob.glob(os.path.join(ROOT, "7_ASSETS", "audio", "bgm", "*.mp3"))):
        stem = os.path.splitext(os.path.basename(path))[0]
        node_id = "as_bgm_" + stem
        add_node(node_id, "BGM: " + stem, "asset")
        add_edge("d_7assets", node_id)
        n += 1
    return n


# ============================================================================ REPO INVENTORY (optional)
def scan_repo_inventory(xlsx_path, own_owner=None, untouched_top_n=30):
    """Optional layer: cross-reference the ~1500-repo inventory xlsx against INGESTION_LOG.md, plus the
    top-priority S-tier repos with NO log entry (real actionable backlog — 'repoBacklog' group). Pass
    own_owner (a GitHub username) to flag that owner's untouched repos distinctly ('repoOwn' group) —
    generic, no hardcoded identity. Best-effort — skipped gracefully if pandas/the file aren't available."""
    try:
        import pandas as pd
    except Exception:
        print("[gen_knowledge_graph] pandas unavailable — skipping repo-inventory layer")
        return 0
    if not xlsx_path or not os.path.exists(xlsx_path):
        return 0
    log_path = os.path.join(ROOT, "2_KNOWLEDGE", "INGESTION_LOG.md")
    rows, in_rejected = [], False
    for line in open(log_path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("## Rejected"):
            in_rejected = True
            continue
        if not line.startswith("|") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if in_rejected:
            if len(cells) >= 2 and cells[0] != "Source":
                rows.append({"source": cells[0], "what": cells[1], "where": "", "hint": "REJECTED"})
        elif len(cells) >= 4 and cells[1] != "Source":
            rows.append({"source": cells[1], "what": cells[3],
                         "where": cells[4] if len(cells) > 4 else "", "hint": None})

    def classify(what, where, hint):
        if hint:
            return hint
        w = what.upper()
        real_path = bool(re.search(r'(2_knowledge|4_brain|6_sop|7_assets|scripts/|1_agents|\.agents|3_memory)',
                                    where.lower())) and "none" not in where.lower() and "backlog" not in where.lower()
        if "SKIP-DUP" in w or (re.search(r'\bSKIP\b(?!PED)', w) and not real_path):
            return "SKIP"
        if "ADOPTED" in w or "ADOPT-PATTERN" in w or "BUILT" in w or real_path:
            return "BUILT"
        return "REFERENCE"

    pat = re.compile(r'\b([A-Za-z0-9][\w.-]*)/([A-Za-z0-9][\w.-]*)\b')
    candidates = []
    for r in rows:
        verdict = classify(r["what"], r["where"], r["hint"])
        for m in pat.finditer(r["source"]):
            candidates.append((m.group(1), m.group(2), verdict))

    df = pd.read_excel(xlsx_path, sheet_name="Repos_Classified")
    df["Owner_l"] = df["Owner"].astype(str).str.lower()
    df["Name_l"] = df["Name"].astype(str).str.lower()
    df["Repo_l"] = df["Repo/Model"].astype(str).str.lower()
    prio = {"BUILT": 3, "REFERENCE": 2, "SKIP": 1, "REJECTED": 1}
    matched = {}
    for o, n, v in candidates:
        hit = df[(df["Owner_l"] == o.lower()) & ((df["Name_l"] == n.lower()) | (df["Repo_l"] == n.lower()))]
        for idx in hit.index:
            if idx not in matched or prio.get(v, 0) >= prio.get(matched[idx], 0):
                matched[idx] = v

    inv_hub = "d_repoinv"
    add_node(inv_hub, f"Repo Inventory ({len(df)})", "dir")
    add_edge("d_2knowledge", inv_hub)
    cat_hub = {}
    for cat, grp in df.groupby("Category"):
        short = cat.split(" / ")[0].strip()
        cat_id = "rc_" + re.sub(r"\W+", "_", short)
        add_node(cat_id, f"{short} ({len(grp)})", "repocat")
        add_edge(inv_hub, cat_id)
        cat_hub[cat] = cat_id
    verdict_group = {"BUILT": "repoBuilt", "REFERENCE": "repoRef", "SKIP": "repoSkip", "REJECTED": "repoRej"}
    for idx, verdict in matched.items():
        row = df.loc[idx]
        node_id = f"rp_{row['Owner']}_{row['Name'].split('/')[-1]}"
        add_node(node_id, f"{row['Owner']}/{row['Name'].split('/')[-1]}", verdict_group[verdict])
        add_edge(cat_hub.get(row["Category"], inv_hub), node_id)

    # Actionable backlog: top-priority S-tier repos with NO log entry at all.
    try:
        top = pd.read_excel(xlsx_path, sheet_name="Top_Priority")
    except Exception:
        top = None
    n_untouched = 0
    if top is not None:
        matched_names = {df.loc[i, "Name"].lower() for i in matched}
        top["name_l"] = top["Name"].astype(str).str.lower()
        untouched = top[~top["name_l"].isin(matched_names)].sort_values("Priority Score", ascending=False)
        for _, row in untouched.head(untouched_top_n).iterrows():
            is_own = bool(own_owner) and str(row["Owner"]).lower() == own_owner.lower()
            node_id = f"ru_{row['Owner']}_{row['Name'].split('/')[-1]}"
            title = f"{row['Owner']}/{row['Name'].split('/')[-1]} — Priority {int(row['Priority Score'])}"
            if is_own:
                title += " — OWN REPO"
            add_node(node_id, f"{row['Owner']}/{row['Name'].split('/')[-1]}",
                      "repoOwn" if is_own else "repoBacklog", title=title)
            add_edge(cat_hub.get(row["Category"], inv_hub), node_id)
            n_untouched += 1
    return len(matched) + n_untouched


def sync_html():
    """Inject the CURRENT nodes/edges (single source of truth) into docs/SYSTEM_MAP.html between its
    markers, replacing the old hand-written duplicate. Best-effort — skipped if the file/markers are missing."""
    if not os.path.exists(HTML_PATH):
        print("[gen_knowledge_graph] SYSTEM_MAP.html not found — skipping HTML sync")
        return False
    html = open(HTML_PATH, encoding="utf-8").read()
    if HTML_START not in html or HTML_END not in html:
        print("[gen_knowledge_graph] WARNING: SYSTEM_MAP.html markers not found — HTML sync skipped "
              "(the graph view there is now STALE; check the markers weren't edited away)")
        return False
    pre, rest = html.split(HTML_START, 1)
    _, post = rest.split(HTML_END, 1)
    block = (HTML_START +
             f"  const nodes = {json.dumps(nodes, ensure_ascii=False)};\n"
             f"  const edges = {json.dumps(edges, ensure_ascii=False)};\n" +
             HTML_END)
    open(HTML_PATH, "w", encoding="utf-8").write(pre + block + post)
    print(f"[gen_knowledge_graph] synced {len(nodes)} nodes / {len(edges)} edges into {HTML_PATH}")
    return True


def main():
    ap = argparse.ArgumentParser(description="Generate SEOSONA's queryable knowledge graph")
    ap.add_argument("--inventory", help="optional path to repo_inventory xlsx (adds the repo layer)")
    ap.add_argument("--own-owner", help="GitHub username to flag distinctly among untouched backlog repos")
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--no-html-sync", action="store_true", help="skip updating docs/SYSTEM_MAP.html")
    a = ap.parse_args()

    scan_dirs()
    n_sop = scan_sops()
    n_brain = scan_brain_modules()
    n_pipelines = scan_pipelines()
    n_agents = scan_agents()
    n_skills = scan_skills()
    n_skill_modules = scan_skill_modules()
    n_templates = scan_templates()
    n_components = scan_components()
    n_effects = scan_effects()
    n_domain = scan_domain_skills()
    n_assets = scan_assets()
    n_repos = scan_repo_inventory(a.inventory, own_owner=a.own_owner)

    out = {"nodes": nodes, "edges": edges,
           "meta": {"generated": datetime.now().isoformat(timespec="seconds"),
                    "node_count": len(nodes), "edge_count": len(edges)}}
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    json.dump(out, open(a.out, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    print(f"[gen_knowledge_graph] {len(nodes)} nodes, {len(edges)} edges -> {a.out}")
    print(f"  SOPs:{n_sop}  brain-modules:{n_brain}  pipelines:{n_pipelines}  agents+personas:{n_agents}  "
          f"skills:{n_skills}  skill-modules:{n_skill_modules}  templates:{n_templates}  "
          f"components:{n_components}  effects:{n_effects}  "
          f"domain-skills:{n_domain}  assets:{n_assets}" + (f"  repos:{n_repos}" if n_repos else ""))
    if not a.no_html_sync:
        sync_html()


if __name__ == "__main__":
    main()
